/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

import modeloqytetet.Calle;
import modeloqytetet.Casilla;
import modeloqytetet.Especulador;
import modeloqytetet.Jugador;
import modeloqytetet.OtraCasilla;
import modeloqytetet.Qytetet;
import modeloqytetet.Sorpresa;
import modeloqytetet.TipoSorpresa;
import modeloqytetet.TituloPropiedad;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class VistaQytetet extends javax.swing.JPanel {

    /**
     * Creates new form VistaQytetet
     */
    public VistaQytetet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaCartaSorpresa1 = new GUIQytetet.VistaCartaSorpresa();
        vistaCasilla1 = new GUIQytetet.VistaCasilla();
        vistaJugador1 = new GUIQytetet.VistaJugador();

        setBackground(new java.awt.Color(47, 39, 54));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 39, 54)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vistaJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vistaCasilla1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addComponent(vistaCartaSorpresa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vistaCasilla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaCartaSorpresa1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void actualizar(Qytetet partida) {
        String t_casilla = "",
                t_jugador = "",
                t_carta = "";

//______________________________________________________________________________
        Jugador jug = partida.getJugadorActual();

        t_jugador += jug.getNombre() + "\n";

        if (jug instanceof Especulador) {
            t_jugador += "El jugador es ESPECULADOR y su factor es: 2\n";
        }

        t_jugador += jug.getSaldo() + " rupias\n";

        if (jug.isEncarcelado()) {
            t_jugador += "Está encarcelado\n";
        } else {
            t_jugador += "Es libre\n";
        }

        if (jug.tengoPropiedades()) {
            t_jugador += "Propiedades:\n";
            for (TituloPropiedad tit : jug.getPropiedades()) {
                t_jugador += "\t" + tit.getCasilla().getNumeroCasilla() + " " + tit.getNombre() + "\n";
            }
        } else {
            t_jugador += "No tienes propiedades\n";
        }

//______________________________________________________________________________
        Casilla cas = jug.getCasillaActual();
        if (cas.soyEdificable()) {
            Calle calle = ((Calle) cas);
            t_casilla += "Calle: " + calle.getNumeroCasilla() + " " + calle.getTitulo().getNombre() + "\n"
                    + "Precio: " + calle.getCoste() + " rupias\n"
                    + calle.getNumCasas() + "casa/s\n"
                    + calle.getNumHoteles() + "hotel/es\n"
                    + "Alquiler base: " + calle.getTitulo().getAlquilerBase() + "\n";

            if (calle.tengoPropietario()) {
                t_casilla += "Propietario: " + calle.getTitulo().getPropietario().getNombre() + "\n";
                if (calle.estaHipotecada()) {
                    t_casilla += "HIPOTECADA\n";
                }
            }

            t_casilla += "\n\n Coste edificar: " + calle.getTitulo().getPrecioEdificar();
        }
        else
        {
            OtraCasilla otra = ((OtraCasilla)cas);
            t_casilla += otra.getNumeroCasilla() + " " + otra.getTipo() + "\n";
        }

//______________________________________________________________________________
        Sorpresa carta = partida.getCartaActual();
        if(carta != null)
        {
            t_carta += carta.getTexto() + "\n";

            if (carta.getTipo() != TipoSorpresa.SALIRCARCEL && carta.getTipo() != TipoSorpresa.CONVERTIRME) {
                t_carta += "Valor: " + carta.getValor() + "\n";
            }
        }

        vistaJugador1.actualizar(t_jugador);
        vistaCasilla1.actualizar(t_casilla);
        vistaCartaSorpresa1.actualizar(t_carta);
        this.repaint(); //Investiga para qué sirven estos métodos
        this.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIQytetet.VistaCartaSorpresa vistaCartaSorpresa1;
    private GUIQytetet.VistaCasilla vistaCasilla1;
    private GUIQytetet.VistaJugador vistaJugador1;
    // End of variables declaration//GEN-END:variables
}
